#!/bin/sh
# a little script supposed to run as root,
# updating the system, showing current status
# and shuts down automatically as htop is quit.

apt-get update
apt-get upgrade -y
apt-get dist-upgrade -y
htop
shutdown -P 1
