
# shown on i3status-rs without is-interactive
# function on_exit --on-process %self --is-interactive
#   echo "fish is now exiting"
# end

function fish_greeting
#  echo "If you can't do it, who will?"
#  set ran random
  fortune -as | cowthink
  echo
end

if status --is-interactive
  echo "-- (tux) --"
  echo "Think about reading a page or more today!"
end



set -x PATH ~/.local/bin $PATH
set -x PATH ~/.cargo/bin $PATH


# set for factis-environment
# set -x way f
# set -x DOCKER_HOST tcp://127.0.0.1:2375
#

# transset --id $WINDOWID >/dev/null



# This script was automatically generated by the broot function
# More information can be found in https://github.com/Canop/broot

# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br
    set f (mktemp)
    broot --outcmd $f $argv
    if test $status -ne 0
        rm -f "$f"
        return "$code"
    end
    set d (cat "$f")
    rm -f "$f"
    eval "$d"
end

# # defined in /usr/share/fish/functions/fish_prompt.fish @ line 4
# function fish_prompt --description 'write out the prompt'
#     set -l last_pipestatus $pipestatus
#     set -l normal (set_color normal)
#
#   # color the prompt differently when we're root
#     set -l color_cwd $fish_color_cwd
#     set -l prefix
#     set -l suffix '>'
#     if contains -- $user root toor
#         if set -q fish_color_cwd_root
#             set color_cwd $fish_color_cwd_root
#         end
#         set suffix '#'
#     end
#
#   # if we're running via ssh, change the host color.
#     set -l color_host $fish_color_host
#     if set -q ssh_tty
#         set color_host $fish_color_host_remote
#     end
#
#   # write pipestatus
#     set -l prompt_status (__fish_print_pipestatus " [" "]" "|" (set_color $fish_color_status) (set_color --bold $fish_color_status) $last_pipestatus)
#
#   echo -n -s (set_color $fish_color_user) "$user" $normal @ (set_color $color_host) (prompt_hostname) $normal ' ' (set_color $color_cwd) (prompt_pwd) $normal (fish_vcs_prompt) $normal $prompt_status $suffix " "
# end

