---

# passive_update templating and cron setup
# - name: Template passive_update.sh
#   template:
#     src: templates/passive_update.j2
#     dest: ~/passive_update.sh
#     mode: 0500 # u=rx

- name: Set up Cronjob to update repositories
  ansible.builtin.cron:
    name: Passively update common Repositories
    minute: "0"
    user: "{{ username }}"
    job: "~/passive_update.sh"
  when: not link_nixos
