---
- name: Restart SSH
  systemd:
    name: ssh
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
  when: not ansible_check_mode

- name: Update GRUB
  command: update-grub
  changed_when: true
